### ISSUE TITLE
Remove commands

### ISSUE THREAD

**Issue by 3174N** [iSaluki/discord-slash-commands#1]
The script currently does not have a way to remove slash commands. Are there any plans to add one?

**Comment by iSaluki** [comment]
Hello,

Thanks for the suggestion. I will get this implemented as soon as possible.

**Comment by iSaluki** [comment]
In the latest commit, I have added functionality to get commands (the first ID in the get is the ID of the command, which can be used to delete the command.  It also adds the functionality to delete commands. Both getting and deleting commands should work for guilds and globally. Please let me know if there are any issues with this system.
