### ISSUE TITLE
Add an all guilds variable for guild_ids variable when making slash commands

### ISSUE THREAD

**Issue by JakeS-dot** [iSaluki/discord-slash-commands#6]

**Comment by iSaluki** [comment]
I believe this already exists. When running the program, you can specify whether you want to use a Guild ID or Global. Let me know if you mean something else or have found a bug though.

**Comment by JakeS-dot** [comment]
Thanks! Kindly appreciated.

**Comment by iSaluki** [comment]
Glad this solved your problem! :)
